# Generated by Django 2.2.12 on 2020-06-08 08:21

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('_id', models.CharField(default='98cc1d1ea99e4f1a8ce124cb783a6d81', max_length=100, primary_key=True, serialize=False)),
                ('receipt', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'intents',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='SampleKeyword',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=200)),
                ('newkeywords', models.CharField(blank=True, max_length=200)),
                ('intentId', models.ForeignKey(db_column='intentId', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.Intent')),
            ],
            options={
                'db_table': 'keyword_samples',
            },
        ),
    ]
