# Generated by Django 2.2.12 on 2020-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='_id',
            field=models.CharField(default='a6f480d6c35b4d70836acd7ddbe34664', max_length=100, primary_key=True, serialize=False),
        ),
    ]
