# Generated by Django 3.0.6 on 2020-05-15 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIntent', models.CharField(max_length=100)),
                ('content', models.TextField(default='no content', max_length=100)),
                ('countOldKey', models.DecimalField(decimal_places=0, max_digits=10)),
                ('countNewKey', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Intent')),
            ],
        ),
    ]
