# Generated by Django 3.0.6 on 2020-05-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intent',
            old_name='content',
            new_name='intent',
        ),
        migrations.RenameField(
            model_name='intent',
            old_name='idIntent',
            new_name='intentId',
        ),
    ]
