# Generated by Django 3.0.6 on 2020-05-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200515_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='intentId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='newkeyword',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Intent', to_field='intentId'),
        ),
    ]
