# Generated by Django 3.0.6 on 2020-05-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200515_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Intent', to_field='intentId'),
        ),
    ]
